spring:
  application:
    name: urlshortener

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/urlshortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:VerySecretKeyVerySecretKeyVerySecretKey123}
  expiration: ${JWT_EXPIRATION:3600000}